# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rspec_rails_scaffold_templates 3.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rspec_rails_scaffold_templates".freeze
  s.version = "3.3.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Dimitri Kulk".freeze]
  s.date = "2025-03-15"
  s.description = "RSpec scaffold generator templates that use FactoryGirl and WiceGrid".freeze
  s.email = "dimitri@kulk.eu".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rspec_rails_scaffold_templates.rb",
    "lib/rspec_rails_scaffold_templates/generators/integration_generator.rb",
    "lib/rspec_rails_scaffold_templates/generators/scaffold_generator.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/integration/request_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/api_controller_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/api_request_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/controller_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/edit_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/index_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/new_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/request_spec.rb",
    "lib/rspec_rails_scaffold_templates/generators/templates/rspec/scaffold/show_spec.rb",
    "rspec_rails_scaffold_templates.gemspec",
    "spec/rspec_rails_scaffold_templates_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dima4p/rspec_rails_scaffold_templates".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.5.22".freeze
  s.summary = "RSpec scaffold generator templates that use FactoryGirl and WiceGrid".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<rspec>.freeze, ["~> 3.1".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.1".freeze])
  s.add_development_dependency(%q<bundler>.freeze, ["~> 2.3.9".freeze])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0".freeze])
  s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.0".freeze])
end

